- src/main/java/Backend/teampplus/common/entity/DeleteStatus.java
- src/main/java/Backend/teampplus/deploy/HelloController.java
- src/main/java/Backend/teampplus/domain/domain.java
- src/main/java/Backend/teampplus/global/common/entity/DeleteStatus.java
- src/main/java/Backend/teampplus/global/common/entity/PeriodBaseEntity.java
- src/main/java/Backend/teampplus/global/common/entity/TimeBaseEntity.java
- src/main/java/Backend/teampplus/global/common/entity/UserBaseEntity.java
- src/main/java/Backend/teampplus/global/common/response/CommonResponse.java
- src/main/java/Backend/teampplus/global/config/ModelMapperConfig.java
- src/main/java/Backend/teampplus/global/config/S3Config.java
- src/main/java/Backend/teampplus/global/config/SwaggerConfig.java
- src/main/java/Backend/teampplus/global/error/ErrorCode.java
- src/main/java/Backend/teampplus/global/error/GlobalExceptionHandler.java
- src/main/java/Backend/teampplus/global/error/exception/BadRequestException.java
- src/main/java/Backend/teampplus/global/error/exception/BaseException.java
- src/main/java/Backend/teampplus/global/error/exception/ForbiddenException.java
- src/main/java/Backend/teampplus/global/error/exception/InternalServerException.java
- src/main/java/Backend/teampplus/global/error/exception/NotFoundException.java
- src/main/java/Backend/teampplus/global/error/exception/UnauthorizedException.java
- src/main/java/Backend/teampplus/global/swagger/SwaggerController.java
- src/main/java/Backend/teampplus/infra/s3/S3Controller.java
- src/main/java/Backend/teampplus/infra/s3/S3Service.java
---
디렉토리 구조 리팩토링
---
refactor/directorystructure
---
#4 
---
> 🔨 refac(directorystructure): 도메인형 디렉토리 구조로 변경

- src/main/java/Backend/teampple/TeamppleApplication.java
- src/main/java/Backend/teampple/domain/stages/StagesRepository.java
- src/main/java/Backend/teampple/domain/stages/dto/request/PostStageDto.java
- src/main/java/Backend/teampple/domain/stages/entity/Stage.java
- src/main/java/Backend/teampple/domain/teams/TeammateRepository.java
- src/main/java/Backend/teampple/domain/teams/TeamsController.java
- src/main/java/Backend/teampple/domain/teams/TeamsRepository.java
- src/main/java/Backend/teampple/domain/teams/TeamsService.java
- src/main/java/Backend/teampple/domain/teams/dto/request/PostTeamDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeamDetailDto.java
- src/main/java/Backend/teampple/domain/teams/entity/Team.java
- src/main/java/Backend/teampple/domain/teams/temp.java
- src/main/java/Backend/teampple/global/common/entity/PeriodBaseEntity.java
- src/main/java/Backend/teampple/global/common/response/CommonResponse.java
- src/main/java/Backend/teampple/global/error/ErrorCode.java
- src/main/java/Backend/teampple/global/error/GlobalExceptionHandler.java
- src/main/resources/application.yml
---
팀플 생성 api, 팀플 상세 정보 조회 api 구현 및 스웨거 추가
---
feature/team
---
#12 
---
auth 로직 추가되면 검증 로직 추가하겠습니다.
> 🚀 feat : team 조회, 정보 조회 API

- src/main/java/Backend/teampple/domain/feedbacks/entity/Feedback.java
- src/main/java/Backend/teampple/domain/stages/StagesRepository.java
- src/main/java/Backend/teampple/domain/stages/entity/Stage.java
- src/main/java/Backend/teampple/domain/tasks/TasksRepository.java
- src/main/java/Backend/teampple/domain/tasks/entity/Task.java
- src/main/java/Backend/teampple/domain/teams/TeamsController.java
- src/main/java/Backend/teampple/domain/teams/TeamsService.java
- src/main/java/Backend/teampple/domain/teams/dto/request/PutTeamDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeamTasksDto.java
- src/main/java/Backend/teampple/domain/teams/entity/Team.java
- src/main/resources/application.yml
---
team 상세 정보 조회, 정보 수정 API 구현
feature/team
---
작업 브랜치
---
#16 
---
특이사항
> 🚀 feat : team 상세 정보 조회, 정보 수정 API

- src/main/java/Backend/teampple/domain/files/FilesController.java
- src/main/java/Backend/teampple/domain/stages/StagesController.java
- src/main/java/Backend/teampple/domain/stages/StagesService.java
- src/main/java/Backend/teampple/domain/tasks/dto/response/GetTaskBriefDto.java
- src/main/java/Backend/teampple/domain/teams/TeamsController.java
- src/main/java/Backend/teampple/domain/teams/TeamsService.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetScheduleDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeamDetailDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeamTasksDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeammateDto.java
- src/main/java/Backend/teampple/global/config/SwaggerConfig.java
- src/main/resources/application.yml
---
* dto swagger 수정
* param 수정
---
refac/swagger
---
#30 
---
> 🔨 refactor - swagger 수정

- src/main/generated/Backend/teampple/domain/auth/mapper/RequestOAuthTokenMapperImpl.java
- src/main/generated/Backend/teampple/domain/users/mapper/request/GetUserProfileMapperImpl.java
- src/main/generated/Backend/teampple/domain/users/mapper/response/PostUserProfileMapperImpl.java
- src/main/generated/Backend/teampple/domain/users/mapper/response/PutUserProfileMapperImpl.java
- src/main/java/Backend/teampple/domain/auth/AuthController.java
- src/main/java/Backend/teampple/domain/auth/AuthService.java
- src/main/java/Backend/teampple/domain/auth/AuthServiceImpl.java
- src/main/java/Backend/teampple/domain/auth/dto/request/RequestOAuthTokenDto.java
- src/main/java/Backend/teampple/domain/auth/dto/request/RequestSignUpDto.java
- src/main/java/Backend/teampple/domain/auth/dto/response/ResponseTokenDto.java
- src/main/java/Backend/teampple/domain/auth/jwt/JwtTokenProvider.java
- src/main/java/Backend/teampple/domain/auth/mapper/RequestOAuthTokenMapper.java
- src/main/java/Backend/teampple/domain/users/entity/UserProfile.java
- src/main/java/Backend/teampple/domain/users/mapper/response/PostUserProfileMapper.java
- src/main/java/Backend/teampple/domain/users/service/UserProfileService.java
- src/main/java/Backend/teampple/domain/users/service/UserProfileServiceImpl.java
---
1. 회원가입 바디 오류 해결 -> dto signup으로 합치고 mapper(=mapStruct)로 유저 프로파일과 토큰값 분리
2. default값 등록 오류 빌더에 로직 추가하여 해결
---
refac/auth
---
#43 
---
default값 임시 해결하였으나 이 방법이 맞는지는 고민이 필요함
또한 회원가입 json구조를 좀 더 보기 좋게 바꿀수 없는지 고민
> 🔨  [Refac] auth 관련 이슈 중 회원가입 이슈 해결

- src/main/java/Backend/teampple/global/error/ErrorCode.java
- src/main/java/Backend/teampple/global/error/GlobalExceptionHandler.java
- src/main/java/Backend/teampple/infra/s3/S3Controller.java
- src/main/java/Backend/teampple/infra/s3/S3Service.java
- src/main/java/Backend/teampple/infra/s3/dto/GetS3UrlDto.java
---
* presigned url 구현
* s3 관련 에러 정리
---
feat/presignedurl
---
#55 
---
> 🚀 feat : presigned url 구현

- src/main/java/Backend/teampple/domain/feedbacks/dto/response/GetFeedbackBriefDto.java
- src/main/java/Backend/teampple/domain/feedbacks/entity/FeedbackOwner.java
- src/main/java/Backend/teampple/domain/feedbacks/repository/FeedbackOwnerRespository.java
- src/main/java/Backend/teampple/domain/tasks/TasksController.java
- src/main/java/Backend/teampple/domain/tasks/TasksService.java
- src/main/java/Backend/teampple/domain/tasks/entity/Task.java
- src/main/java/Backend/teampple/domain/tasks/repository/TasksRepository.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeamStageDto.java
- src/main/java/Backend/teampple/domain/users/service/UserServiceImpl.java
- src/main/java/Backend/teampple/global/common/validation/CheckUser.java
- src/main/java/Backend/teampple/global/common/validation/dto/UserTaskDto.java
---
* 작업 완료 토글 버튼용 api 추가
* user task, feedback api의 response dto 자료 추가
---
feat/task
---
#57 
---
> 🚀 feat - 토글 버튼용 API, Dto 자료 추가

- src/main/java/Backend/teampple/domain/feedbacks/dto/response/GetFeedbackBriefDto.java
- src/main/java/Backend/teampple/domain/stages/repository/StagesRepository.java
- src/main/java/Backend/teampple/domain/tasks/dto/response/GetTaskBriefDto.java
- src/main/java/Backend/teampple/domain/tasks/repository/TasksRepository.java
- src/main/java/Backend/teampple/domain/teams/TeamsController.java
- src/main/java/Backend/teampple/domain/teams/TeamsService.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeamStageDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeamTasksDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/PostTeamResDto.java
- src/main/java/Backend/teampple/domain/users/service/UserServiceImpl.java
---
/users/tasks get
/users/feedbacks get
/teams post
/teams/tasks get
api response 수정
---
fix/dto
---
#65 
---
> 🔨[Fix] - response dto 수정

- src/main/java/Backend/teampple/domain/templates/TemplatesService.java
---
template 버그 수정
---
fix/template
---
#67 
---
> 🔨 fix(template) : template 버그 수정

- src/main/java/Backend/teampple/domain/auth/security/SecurityConfig.java
- src/main/java/Backend/teampple/domain/example/ExampleController.java
- src/main/java/Backend/teampple/global/common/response/CommonResponse.java
- src/main/java/Backend/teampple/global/config/SwaggerConfig.java
- src/main/java/Backend/teampple/global/error/ErrorCode.java
- src/main/java/Backend/teampple/global/error/ErrorResponse.java
- src/main/java/Backend/teampple/global/error/GlobalExceptionHandler.java
---
error response, swagger 수정
---
refac/error
---
#70 
---
/example/error에 모든 에러 표시할 예정
> 🔨 [Refac] error response, swagger 수정

- src/main/java/Backend/teampple/domain/tasks/TasksService.java
---
task 등록 api 
operator를 teammate id로 여기도록 변경
---
hotfix/tasks
---
#76 
---
> 🐞 hotfix(task) : task 등록 api 장애 해결

- src/main/java/Backend/teampple/domain/tasks/TasksService.java
- src/main/java/Backend/teampple/domain/tasks/repository/OperatorRepository.java
- src/main/java/Backend/teampple/domain/teams/repository/TeammateRepository.java
---
* task 수정 api 장애 해결
* task put api 로직 변경
---
hotfix/tasks
---
#76 
---
> 🐞 hotfix(task) : task 수정 api 장애 해결

- src/main/java/Backend/teampple/domain/auth/oauth/OAuthSuccessHandler.java
---
작업 사항
---
작업 브랜치
---
이슈 번호
---
특이사항
> :lady_beetle: bug(oauth): fix redirect #86

- src/main/java/Backend/teampple/domain/users/service/UserServiceImpl.java
---
api task get api 에러 처리
---
fix/user
---
- close #88 
---
> 🔨 fix(user) : api task get api 에러 처리

- src/main/java/Backend/teampple/domain/invitations/InvitationService.java
- src/main/java/Backend/teampple/domain/teams/TeamsService.java
- src/main/java/Backend/teampple/domain/teams/dto/TeammateDto.java
- src/main/java/Backend/teampple/domain/teams/dto/response/GetTeammateDto.java
- src/main/java/Backend/teampple/domain/teams/repository/TeammateRepository.java
- src/main/java/Backend/teampple/domain/users/service/UserServiceImpl.java
- src/main/java/Backend/teampple/global/error/ErrorCode.java
---
* 팀플 종료 기준 수정
* 초대 url 수정
---
hotfix/team
---
> 🐞 hotfix(task) : 종료 팀플 구분 에러, 초대 링크 에러

- src/main/java/Backend/teampple/domain/auth/oauth/OAuthSuccessHandler.java
- src/main/java/Backend/teampple/domain/teams/TeamsService.java
- src/main/resources/application.yml
---
작업 사항
---
작업 브랜치
---
이슈 번호
---
특이사항
> Sync! 및 수정사항 업데이트 

- src/main/java/Backend/teampple/domain/auth/oauth/OAuthSuccessHandler.java
---
summary와 일치함
---
bug/auth
---
#86
---
특이사항
> :hammer: redirect add param!

- src/main/java/Backend/teampple/domain/auth/oauth/OAuthSuccessHandler.java
---
redirect url 체킹
---
bug/auth
---
이슈 번호
---
특이사항
> :hammer: fix redirectURL

- src/main/java/Backend/teampple/domain/teams/entity/Schedule.java
- src/main/java/Backend/teampple/domain/teams/entity/Teammate.java
---
schedule, teammate entity에 ondelete cascade 설정
---
hotfix/schedule
---
- close #91 
---
> 🐞 hotfix(team) : 팀 삭제 에러 해결

- .github/workflows/dev-deploy.yml
- docker-compose.yml
- src/main/java/Backend/teampple/global/config/RedisConfig.java
- src/main/java/Backend/teampple/global/config/redis/redis_6379.conf
- src/main/java/Backend/teampple/global/config/redis/redis_6380.conf
- src/main/java/Backend/teampple/global/config/redis/redis_6381.conf
- src/main/java/Backend/teampple/global/config/redis/sentinal_16379.conf
- src/main/java/Backend/teampple/global/config/redis/sentinal_16380.conf
- src/main/java/Backend/teampple/global/config/redis/sentinal_16381.conf
---
redis sentinal 구현
---
feat/redis
---
- #73 
---
> 🚀 feat(redis) : redis sentinal 구현

- src/main/java/Backend/teampple/domain/tasks/repository/OperatorRepository.java
- src/main/java/Backend/teampple/domain/teams/TeamsController.java
- src/main/java/Backend/teampple/domain/teams/TeamsService.java
- src/main/java/Backend/teampple/domain/users/service/UserServiceImpl.java
---
* 팀플 삭제 로직 수정
* 내 할 일 조회 로직 변경
---
fix/team
---
이슈 번호
- close #107 
---
> 🔨 fix: 팀플 삭제 로직 수정, 내 할 일 조회 로직 변경

- README.md
---
리드미 수정
---
edit/readme
---
이슈 번호
- close #
---
없음~!
> :rocket: edit/readme

- .github/workflows/dev-deploy.yml
- docker-compose.yml
- src/main/java/Backend/teampple/global/config/RedisConfig.java
- src/main/resources/application.yml
---
작업 사항
---
작업 브랜치
---
이슈 번호
- #117 
- #120 
---
특이사항
> 🚀 feat(redis) : redis sentinel 셋팅

- config/redis/sentinel/26379.conf
- config/redis/sentinel/26380.conf
- config/redis/sentinel/26381.conf
---
작업 사항
---
작업 브랜치
---
이슈 번호
- #117 
- #120 
---
특이사항
> 🚀 feat(redis) : redis sentinel 셋팅 31트

- config/redis/sentinel/26379.conf
- config/redis/sentinel/26380.conf
- config/redis/sentinel/26381.conf
- src/main/java/Backend/teampple/domain/auth/AuthServiceImpl.java
- src/main/java/Backend/teampple/domain/auth/jwt/JwtTokenProvider.java
- src/main/java/Backend/teampple/domain/auth/oauth/OAuth2Attribute.java
- src/main/java/Backend/teampple/domain/feedbacks/FeedbacksService.java
- src/main/java/Backend/teampple/domain/invitations/InvitationService.java
- src/main/java/Backend/teampple/domain/templates/BookmarkService.java
- src/main/java/Backend/teampple/global/common/auth/CustomAuthenticationPrincipalArgumentResolver.java
- src/main/java/Backend/teampple/global/common/validation/CheckUser.java
- src/main/java/Backend/teampple/global/error/exception/BadRequestException.java
- src/main/java/Backend/teampple/global/error/exception/ForbiddenException.java
- src/main/java/Backend/teampple/global/error/exception/InternalServerException.java
- src/main/java/Backend/teampple/global/error/exception/NotFoundException.java
- src/main/java/Backend/teampple/global/error/exception/UnauthorizedException.java
---
작업 사항
---
refac/error
---
이슈 번호
- close #150 
---
> 🔨 refac : error response 적용

- config/redis/sentinel/26379.conf
- config/redis/sentinel/26380.conf
- config/redis/sentinel/26381.conf
- src/main/java/Backend/teampple/domain/auth/AuthServiceImpl.java
- src/main/java/Backend/teampple/domain/auth/jwt/JwtTokenProvider.java
- src/main/java/Backend/teampple/domain/auth/oauth/OAuth2Attribute.java
- src/main/java/Backend/teampple/domain/feedbacks/FeedbacksService.java
- src/main/java/Backend/teampple/domain/invitations/InvitationService.java
- src/main/java/Backend/teampple/domain/templates/BookmarkService.java
- src/main/java/Backend/teampple/global/common/auth/CustomAuthenticationPrincipalArgumentResolver.java
- src/main/java/Backend/teampple/global/common/validation/CheckUser.java
- src/main/java/Backend/teampple/global/error/ErrorResponse.java
- src/main/java/Backend/teampple/global/error/GlobalExceptionHandler.java
- src/main/java/Backend/teampple/global/error/exception/BadRequestException.java
- src/main/java/Backend/teampple/global/error/exception/ForbiddenException.java
- src/main/java/Backend/teampple/global/error/exception/InternalServerException.java
- src/main/java/Backend/teampple/global/error/exception/NotFoundException.java
- src/main/java/Backend/teampple/global/error/exception/UnauthorizedException.java
---
작업 사항
---
작업 브랜치
---
이슈 번호
- close #
---
특이사항
> 🔨 refac : error response function 수정
